###
POST http://localhost:3000/product
Content-Type:application/json

{
    "name": "Teclado",
    "price": 40,
    "quantity": 0
}

###
POST http://localhost:3000/product
Content-Type:application/json

{
    "name": "Mouse",
    "price": 30,
    "quantity": 15
}